beam_size: 20
testset: 'A_Thaliana'
optimum_path_file: '/log/optimum_path/A_Thaliana_beam20_sum_test.csv'
output_file: '/log/seq_generation/A_Thaliana_beam20_sum_beam20_sum_test.csv'
data_dir: '/graphnovo_data/overall/'
device: 0
