defaults:
  - preprocessing: all_graph
  - encoder: light
  - decoder: light
  - train: train
  - infer: optimal_path_inference
  - _self_

mode: train
dist: false
task: optimal_path
train_spec_header_path: 
eval_spec_header_path:
train_dataset_dir:
eval_dataset_dir:

wandb:
  entity: graphnovo
  project: graphnovo
  name: pathsearcher

